[package]
name = "mu"
version = "0.1.0"
authors = ["weathfold <weathfold@li-dev.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Generic
simplelog = "*"
log = "*"
specs = "*"
cgmath = "*"
rand = "*"

# Client only
glium = "*"
glutin = "*"
imgui = "*"
imgui-glium-renderer = "*"
imgui-winit-support = "*"